version: "3.3"

services:
  redis-service:
    expose:
      - "6379"
    image: redis:alpine
  api:
    ports:
      - 8000:8000
    build:
      context: .
    volumes:
      - app-db:/src/db/
    command: bash -c "python manage.py migrate && 
                      gunicorn -b 0.0.0.0"
  celery:
    build:
      context: .
    command: celery -A crypto_tracker worker --loglevel=INFO
    environment:
      REDIS_URL: redis://redis-service:6379/0
    depends_on:
      - redis-service
    volumes:
      - app-db:/src/db/
  celery-beat:
    build:
      context: .
    command: celery -A crypto_tracker beat --loglevel=INFO
    environment:
      REDIS_URL: redis://redis-service:6379/0
    depends_on:
      - redis-service
    volumes:
      - app-db:/src/db/

volumes:
     app-db: 