version: "3.3"

services:
  redis-service:
    expose:
      - "6379"
    image: redis:alpine
  api:
    ports:
      - 8000:8000
    build:
      context: .
    volumes:
      - ./db.sqlite3:/src/db.sqlite3
  celery:
    build:
      context: .
    command: celery -A crypto_tracker worker --loglevel=INFO
    environment:
      REDIS_URL: redis://redis-service:6379/0
    depends_on:
      - redis-service
    volumes:
      - ./db.sqlite3:/src/db.sqlite3
  celery-beat:
    build:
      context: .
    command: celery -A crypto_tracker beat --loglevel=INFO
    environment:
      REDIS_URL: redis://redis-service:6379/0
    depends_on:
      - redis-service
    volumes:
      - ./db.sqlite3:/src/db.sqlite3