# Generated by Django 4.0.4 on 2022-05-14 07:34

from django.db import migrations, models
import django.db.models.deletion
from crypto_tracker.api.constants.cypto import Coins

def seed_coins(apps, schema_editor):
    Coin = apps.get_model("api", "Coin")

    for coin in Coins:
        Coin.objects.create(name=coin.name, symbol=coin.value)


def unseed_coins(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('name', models.TextField()),
                ('symbol', models.TextField()),
            ],
            options={
                'db_table': 'coin',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='api.coin')),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.AddConstraint(
            model_name='coin',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_coin_symbol'),
        ),
        migrations.RunPython(seed_coins, unseed_coins)
    ]
